version: "3.8"

services:
  ynor-back:
    image: iadopt/btpc-api:latest
    ports:
      - "8888:8080"
    volumes:
      - btpc-aec-document-processing:/tmp/document-processing
    env_file:
      - .env.docker

  ynor-front:
    image: iadopt/btpc-front:latest
    ports:
      - "3092:3000"
    env_file:
      - .env.docker

  ynor-n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    env_file:
      - .env.docker
    depends_on:
      - ynor-n8n-db

  ynor-n8n-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: n8n
    volumes:
      - n8n-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  btpc-aec-document-processing:
  n8n-db-data: