version: '3.8'

services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    image: core:latest
    container_name: core
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.docker