-- CreateEnum
CREATE TYPE "AI_Provider" AS ENUM ('NOT_SPECIFIED', 'GEMINI', 'OPENAI', 'COHERE', 'ANTHROPIC', 'GROK', 'LLAMA', 'TOGETHERAI', 'MISTRAL', 'FIREWORKS', 'DEEPSEEK');

-- AlterTable
ALTER TABLE "Usage" ADD COLUMN     "provider" "AI_Provider" NOT NULL DEFAULT 'NOT_SPECIFIED';
